### ISSUE TITLE
您好，我可以把应用打包为一个包含playGame.exe的目录

### ISSUE THREAD

**Issue by moneypi** [DeepGeGe/Play-FlappyBird-with-AI-tf2keras#2]
您好，我用的-D参数，可以把该应用打包为一个目录，执行playGame.exe即可正常运行，大小差不多为1.2G，压缩后也有四百多兆，不知道是否符合您的需求；
需要的话可以和我联系；

**Comment by DeepGeGe** [comment]
非常感谢，我一直试图使用-F参数将项目打包成一个.exe文件。或许应该如您所说采用-D参数。此外，根据后面我对我尝试解决使用-F参数打包过程的总结与反思，或许将sys.path.append(current_dir + '/game')代码改成sys.path.append('game/')可以解决打包成一个.exe文件中出现找不到资源、模块的问题。

**Comment by moneypi** [comment]
我刚才又研究了一下，现在可以用-F 全部打包成一个 exe 文件了，大小为450M左右

**Comment by DeepGeGe** [comment]
请问要修改什么地方吗？我原来用-F参数时候，主要是提示找不到wrapped_flappy_bird模块。后面各种查资料，没解决就搁置了。

**Comment by moneypi** [comment]
要修改的地方还挺多的，不知道怎么描述，感觉您具体可能不是找不到那个模块，我也是一边调试一边发现的问题，
具体可以加我微信我把修改后的包发给你，或者我加你都行

**Comment by DeepGeGe** [comment]
谢谢，暂时不需要这个包，后面我再自己去尝试一下。（前面主要是每次打包是可以成功的，但是运行起来不成功，会出现dos窗口闪一下退出情况。要找问题，需要抓到这个很快闪退的dos窗口，因此每次调试都非常麻烦，我找个时间再自己试试。）
